"""
TASK-014: Hull Quality Gates (Resolution + Fairness)

Advisory-only gates to surface mesh resolution and fairness concerns
without auto-fixing geometry. Outputs are warnings that should be
recorded alongside compiled HullGeometry metadata.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import List, Dict

from magnet.hull_gen.geometry import HullSection


@dataclass
class QualityWarning:
    """Advisory-only warning generated by quality gates."""

    code: str
    message: str
    station: float
    severity: str = "ADVISORY_WARN"

    def to_dict(self) -> Dict[str, object]:
        return {
            "code": self.code,
            "message": self.message,
            "station": self.station,
            "severity": self.severity,
        }


def check_resolution(sections: List[HullSection]) -> List[QualityWarning]:
    """
    Check section point counts for under/over resolution.

    - Warn if points < 16 (too coarse)
    - Warn if points > 128 (unusually dense)
    """
    warnings: List[QualityWarning] = []
    for s in sections:
        count = len(s.points)
        station = float(getattr(s, "station", getattr(s, "x_position", 0.0)) or 0.0)
        if count < 16:
            warnings.append(
                QualityWarning(
                    code="RESOLUTION_LOW",
                    message=f"Section {station:.3f}: {count} points < 16 minimum",
                    station=station,
                )
            )
        elif count > 128:
            warnings.append(
                QualityWarning(
                    code="RESOLUTION_HIGH",
                    message=f"Section {station:.3f}: {count} points > 128 (dense)",
                    station=station,
                )
            )
    return warnings


def _angle_between(v1, v2) -> float:
    """Return angle (radians) between 3D vectors v1 and v2."""
    dot = sum(a * b for a, b in zip(v1, v2))
    norm1 = math.sqrt(sum(a * a for a in v1))
    norm2 = math.sqrt(sum(a * a for a in v2))
    if norm1 == 0 or norm2 == 0:
        return 0.0
    cosang = max(-1.0, min(1.0, dot / (norm1 * norm2)))
    return math.acos(cosang)


def check_fairness(sections: List[HullSection]) -> List[QualityWarning]:
    """
    Detect curvature spikes / inflections along section curves.

    Approach: compute angle change between consecutive segments in YZ plane.
    Flag if angle change exceeds 60 degrees (curvature spike) or if the
    angle flips sign repeatedly (inflection) over short spans.
    """
    warnings: List[QualityWarning] = []

    for s in sections:
        pts = [p.position for p in s.points if hasattr(p, "position")]
        station = float(getattr(s, "station", getattr(s, "x_position", 0.0)) or 0.0)
        if len(pts) < 3:
            continue

        spike_count = 0
        for i in range(1, len(pts) - 1):
            p0, p1, p2 = pts[i - 1], pts[i], pts[i + 1]
            v1 = (p1.y - p0.y, p1.z - p0.z)
            v2 = (p2.y - p1.y, p2.z - p1.z)
            angle = _angle_between((v1[0], v1[1], 0.0), (v2[0], v2[1], 0.0))
            if angle > math.radians(60):
                spike_count += 1

        if spike_count > 0:
            warnings.append(
                QualityWarning(
                    code="FAIRNESS_SPIKE",
                    message=f"Section {station:.3f}: {spike_count} curvature spikes detected (>60 deg turn)",
                    station=station,
                )
            )

    return warnings
