/**
 * MAGNET UI Domain Stores
 *
 * Domain-bounded state stores.
 */

// Focus Store
export {
  focusStore,
  setFocusedPanel,
  clearFocus,
  restorePreviousFocus,
  setFocusModeActive,
  excludePanelFromFocus,
  includePanelInFocus,
  lockFocus,
  unlockFocus,
  getFocusState,
  isPanelFocused,
  shouldPanelBlur,
  isFocusLocked,
  getFocusedPanelId,
  hasActiveFocus,
  getPanelBlurIntensity,
  getPanelOpacity,
  type FocusStoreState,
} from './focusStore';

// ARS Store
export {
  arsStore,
  selectRecommendation,
  toggleRecommendationExpansion,
  expandRecommendation,
  collapseRecommendation,
  collapseAllRecommendations,
  setFilterCategory,
  setFilterPriority,
  setSortConfig,
  setARSLoading,
  clearFilters,
  getRecommendations,
  getSelectedRecommendation,
  getFilteredRecommendations,
  getRecommendationsByCategory,
  getRecommendationsByPriority,
  isRecommendationExpanded,
  getPendingCount,
  getARSSummary,
  hasCriticalRecommendations,
  type ARSStoreState,
} from './arsStore';

// Inspector Store
export {
  inspectorStore,
  setActiveTab,
  toggleCategory,
  expandAllCategories,
  collapseAllCategories,
  toggleHierarchyNode,
  setSearchQuery as setInspectorSearchQuery,
  toggleEditableOnly,
  startPropertyEdit,
  updatePendingValue,
  cancelPropertyEdit,
  setPanelWidth,
  toggleHierarchy,
  toggleHistory,
  setInspectorLoading,
  getInspectedComponent,
  getFilteredProperties,
  getPropertiesByCategory,
  getHierarchyTree,
  getNodeChildren,
  isCategoryExpanded,
  isNodeExpanded,
  getPropertyById,
  getRecentHistory,
  isEditing,
  getEditingState,
  type InspectorStoreState,
  type InspectorTab,
  type PropertyDefinition,
  type PropertyValue,
  type HierarchyNode,
  type HistoryEntry,
} from './inspectorStore';

// Command Store
export {
  commandStore,
  openCommandPalette,
  closeCommandPalette,
  toggleCommandPalette,
  setSearchQuery as setCommandSearchQuery,
  setSelectedIndex,
  selectPrevious,
  selectNext,
  setActiveCategory,
  enterParamInputMode,
  setParamValue,
  nextParam,
  previousParam,
  cancelParamInput,
  setCommandResult,
  dismissResult,
  setExecutingCommand,
  getAllCommands,
  getFilteredCommands,
  getCommandById,
  getSelectedCommand,
  getCommandsByCategory,
  getRecentCommands,
  getPinnedCommands,
  isCommandPinned,
  getCurrentParam,
  getParamValues,
  areRequiredParamsFilled,
  getCommandHistory,
  isInParamInputMode,
  isExecuting,
  getLastResult,
  isPaletteOpen,
  type CommandStoreState,
} from './commandStore';

// PRS Store (V1.4 - BRAVO)
export {
  prsStore,
  getPRSState,
  getPhaseStatus,
  getActivePhase,
  getProgress,
  getCompletedCount,
  getApprovedCount,
  isDesignComplete,
  getActiveMilestones,
  getPhasesByStatus,
  canStartPhase,
  canApprovePhase,
  setDesignId,
  setPhaseStatus,
  setActivePhase,
  addPendingApproval,
  removePendingApproval,
  addBlockedPhase,
  removeBlockedPhase,
  addMilestone,
  dismissMilestone,
  clearDismissedMilestones,
  setPRSLoading,
  setPRSError,
  updateLastSync,
  reconcilePRSState,
  resetPRSStore,
  subscribeToPRS,
  PHASE_NAMES,
  type PRSStoreState,
  type PhaseInfo,
  type Milestone,
} from './prsStore';
