"""
magnet/systems/structural/stringer.py

T6.1: Stringer Generator (wrapper).

In MAGNET's existing structural model, "stringers" are represented as
longitudinal stiffeners generated by `magnet.structural.stiffener_generator`.

This module provides a systems-level wrapper consistent with other systems
generators (fuel/electrical/etc.) while reusing the structural generators.
"""

from __future__ import annotations

from typing import List, TYPE_CHECKING

from magnet.structural.grid_generator import StructuralGridGenerator
from magnet.structural.plate_generator import PlateGenerator
from magnet.structural.stiffener_generator import StiffenerGenerator
from magnet.structural.stiffeners import Stiffener

if TYPE_CHECKING:
    from magnet.core.state_manager import StateManager


class StringerGenerator:
    """Generate longitudinal stringers (structural longitudinals)."""

    def __init__(self, state: "StateManager"):
        self.state = state

    def generate(self) -> List[Stiffener]:
        grid = StructuralGridGenerator(self.state).generate()
        plates = PlateGenerator(self.state).generate_all_plates(grid)
        stiff = StiffenerGenerator(self.state)
        return list(stiff.generate_longitudinals(grid, plates))

